#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# after_install.sh - AfterInstall Hook
# Set up configuration, env files, and permissions after deploy
# ═══════════════════════════════════════════════════════════════

set -e

APP_NAME="github-aws-pipeline-app"
APP_DIR="/opt/app"
LOG_FILE="/var/log/codedeploy-${APP_NAME}.log"
ENV_FILE="${APP_DIR}/.env"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a $LOG_FILE
}

log "════════════════════════════════════════"
log "  AFTER INSTALL PHASE STARTED"
log "════════════════════════════════════════"

# ─── Set Permissions ────────────────────────────────────────────
log "Setting file permissions..."
chmod +x ${APP_DIR}/aws/scripts/*.sh
chown -R ec2-user:ec2-user ${APP_DIR} 2>/dev/null || \
  chown -R ubuntu:ubuntu ${APP_DIR} 2>/dev/null || true

# ─── Create .env file ───────────────────────────────────────────
log "Generating environment configuration..."

# Read image URI from deployment manifest
IMAGE_URI=""
if [ -f "${APP_DIR}/deployment-manifest.json" ]; then
  IMAGE_URI=$(python3 -c "import sys, json; d=json.load(open('${APP_DIR}/deployment-manifest.json')); print(d.get('imageUri',''))" 2>/dev/null || echo "")
  IMAGE_TAG=$(python3 -c "import sys, json; d=json.load(open('${APP_DIR}/deployment-manifest.json')); print(d.get('imageTag','latest'))" 2>/dev/null || echo "latest")
fi

cat > $ENV_FILE << EOF
# Auto-generated by CodeDeploy at $(date)
NODE_ENV=production
PORT=3000
HOST=0.0.0.0

# Deployment metadata
APP_VERSION=${IMAGE_TAG:-latest}
DEPLOY_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DEPLOYMENT_ID=${DEPLOYMENT_ID:-unknown}
DOCKER_IMAGE=${IMAGE_URI:-unknown}
IMAGE_TAG=${IMAGE_TAG:-latest}

# AWS Configuration
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
EOF

chmod 600 $ENV_FILE
log "Environment file created at $ENV_FILE"

# ─── Clean up old Docker images ──────────────────────────────────
log "Cleaning up old Docker images to free disk space..."
docker image prune -f --filter "until=72h" 2>/dev/null || true
docker system prune -f --volumes 2>/dev/null || true
log "Docker cleanup complete."

# ─── Verify deployment manifest ──────────────────────────────────
if [ -f "${APP_DIR}/deployment-manifest.json" ]; then
  log "Deployment manifest:"
  cat ${APP_DIR}/deployment-manifest.json | python3 -m json.tool 2>/dev/null || cat ${APP_DIR}/deployment-manifest.json
fi

log "AFTER INSTALL PHASE COMPLETE"
exit 0
